# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
    build:
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.9
            architecture: x64
        - name: Instalar dependências
          run: |
            pip install -r requirements-dev.txt
        - name: Rodar flake8
          uses: py-actions/flake8@v1
          with:
            checkName: 'flake8_py3'
        - name: Rodar Testes Automáticos
          run: |
            pytest --cov=libpythonpro
        - name: Relatório Coverage
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          run: |
            codecov
